
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: fyp_api_container
#    ports:
#      - "8000:8000"  # Map the container's port 5000 to the host's port 5000
#    volumes:
#      - .:/app
#    environment:
#      - PYTHONUNBUFFERED=1
       
